-- Run in the Supabase SQL editor when the local customer-request forms are approved.
create table if not exists public.customer_requests (id bigint generated by default as identity primary key,request_type text not null check (request_type in ('warranty','vehicle_sourcing','service_repair','vehicle_disposition','referral')),first_name text not null,last_name text not null,phone text not null,email text not null,details jsonb not null default '{}'::jsonb,status text not null default 'New' check (status in ('New','Contacted','In Progress','Completed','Cancelled')),created_at timestamptz not null default now());
alter table public.customer_requests enable row level security;
revoke all on table public.customer_requests from anon,authenticated;
grant insert on table public.customer_requests to anon;
grant usage,select on sequence public.customer_requests_id_seq to anon;
drop policy if exists "Public can submit customer requests" on public.customer_requests;
create policy "Public can submit customer requests" on public.customer_requests for insert to anon with check (status='New');
