(()=>{
  const url='https://dpsgtliddmdvfwjahkkq.supabase.co',key='sb_publishable_f-MRqpvq-FGsxQ7dBNIyKQ_r8MB1VM0';
  const db=supabase.createClient(url,key),$=id=>document.getElementById(id);
  const demo={id:'DEMO-NOT-SAVED',first_name:'Demo',last_name:'Applicant',phone:'204-555-0100',email:'demo@example.test',date_of_birth:'1990-01-01',marital_status:'Single',address:'123 Example Street',city:'Winnipeg',province:'MB',postal_code:'R3T 0A1',address_duration:'1 year, 4 months',previous_address:'45 Previous Avenue',previous_city:'Winnipeg',previous_province:'MB',previous_postal_code:'R2M 1A1',previous_address_duration:'3 years',housing_status:'Renting',housing_payment:1500,employment_status:'Full-time',employer:'Example Company',occupation:'Demo Analyst',employment_duration:'1 year',previous_employer:'Previous Company',previous_occupation:'Sales Associate',previous_employment_duration:'4 years',monthly_income:5500,bankruptcy:'No',repossession:'No',credit_rating:'Good',vehicle_interest:'DEMO VEHICLE — UI TEST',vehicle_price:25000,down_payment:3000,trade_in:'No',trade_value:0,has_cosigner:true,cosigner_first_name:'Demo',cosigner_last_name:'Co-signer',cosigner_phone:'204-555-0199',cosigner_email:'cosigner@example.test',cosigner_employment_status:'Employed',cosigner_employer:'Example Employer',cosigner_occupation:'Supervisor',cosigner_monthly_income:4800,credit_consent:true,marketing_consent:false,consented_at:new Date().toISOString(),notes:'DEMO APPLICATION — NOT A REAL CUSTOMER. This record is not stored in the database.',status:'Demo',created_at:new Date().toISOString()};
  const sections=[
    ['Applicant information',[['first_name','First name'],['last_name','Last name'],['date_of_birth','Date of birth','date'],['marital_status','Marital status'],['phone','Phone'],['email','Email']]],
    ['Current residence',[['address','Street address','wide'],['city','City'],['province','Province'],['postal_code','Postal code'],['address_duration','Time at address'],['housing_status','Housing status'],['housing_payment','Monthly housing payment','money']]],
    ['Previous residence',[['previous_address','Street address','wide'],['previous_city','City'],['previous_province','Province'],['previous_postal_code','Postal code'],['previous_address_duration','Time at previous address']]],
    ['Current employment',[['employment_status','Employment status'],['employer','Employer'],['occupation','Occupation'],['employment_duration','Employment duration'],['monthly_income','Gross monthly income','money']]],
    ['Previous employment',[['previous_employer','Previous employer'],['previous_occupation','Previous occupation'],['previous_employment_duration','Employment duration']]],
    ['Financial background',[['credit_rating','Self-reported credit'],['bankruptcy','Bankruptcy'],['repossession','Repossession']]],
    ['Vehicle and purchase',[['vehicle_interest','Vehicle of interest','wide'],['vehicle_price','Vehicle price','money'],['down_payment','Down payment','money'],['trade_in','Trade-in'],['trade_value','Estimated trade value','money']]],
    ['Co-signer',[['has_cosigner','Co-signer included','yesno'],['cosigner_first_name','First name'],['cosigner_last_name','Last name'],['cosigner_date_of_birth','Date of birth','date'],['cosigner_phone','Phone'],['cosigner_email','Email'],['cosigner_address','Address','wide'],['cosigner_city','City'],['cosigner_province','Province'],['cosigner_postal_code','Postal code'],['cosigner_employment_status','Employment status'],['cosigner_employer','Employer'],['cosigner_occupation','Occupation'],['cosigner_monthly_income','Gross monthly income','money']]],
    ['Consent and notes',[['credit_consent','Credit consent','consent'],['marketing_consent','Marketing consent','consent'],['consented_at','Consent recorded','datetime'],['notes','Applicant notes','wide']]]
  ];
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const isPresent=value=>value!==null&&value!==undefined&&value!=='';
  const money=value=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',minimumFractionDigits:2}).format(Number(value)||0);
  const date=value=>isPresent(value)?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('en-CA',{year:'numeric',month:'long',day:'numeric'}):'—';
  const datetime=value=>isPresent(value)?new Date(value).toLocaleString('en-CA',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
  function display(value,type){if(type==='money')return money(value);if(type==='date')return date(value);if(type==='datetime')return datetime(value);if(type==='yesno'||type==='consent')return value?'Yes':'No';return isPresent(value)?String(value):'—'}
  function dataItem(row,[field,label,type]){const value=display(row[field],type),wide=type==='wide'?' wide':'',consent=type==='consent'?(row[field]?' finance-consent-yes':' finance-consent-no'):'';return `<div class="finance-data-item${wide}"><span>${esc(label)}</span><strong class="${consent.trim()}">${esc(value)}</strong></div>`}
  function section(row,[heading,fields]){const visible=fields.filter(([field])=>isPresent(row[field]));if(!visible.length)return'';return `<section class="finance-section"><h3>${esc(heading)}</h3><div class="finance-data-grid">${visible.map(field=>dataItem(row,field)).join('')}</div></section>`}
  function application(row,isDemo){const name=`${row.first_name||''} ${row.last_name||''}`.trim()||'Unnamed applicant',created=datetime(row.created_at);return `<details class="finance-application"><summary class="finance-application-summary"><div class="finance-applicant-name"><span class="eyebrow red">${isDemo?'DEMO APPLICATION':'FINANCE APPLICATION'}</span><h2>${esc(name)}</h2><p>Submitted ${esc(created)}</p></div><div class="finance-summary-item"><span>Status</span><strong class="finance-status">${esc(row.status||'New')}</strong></div><div class="finance-summary-item"><span>Vehicle</span><strong>${esc(row.vehicle_interest||'Not specified')}</strong></div><div class="finance-summary-item"><span>Phone</span><strong>${esc(row.phone||'—')}</strong></div><span class="finance-summary-arrow" aria-hidden="true">⌄</span></summary><div class="finance-application-body">${sections.map(item=>section(row,item)).join('')}<p class="finance-application-id">Application ID: ${esc(row.id)}</p></div></details>`}
  function render(rows,isDemo=false){$('list').innerHTML=(isDemo?'<p class="finance-demo-note"><strong>Demo mode:</strong> This fictional application is displayed only to preview the organized layout.</p>':'')+(rows.length?rows.map(row=>application(row,isDemo)).join(''):'<div class="finance-admin-empty">No finance applications have been submitted yet.</div>')}
  async function load(){
    $('list').innerHTML='<div class="finance-admin-empty">Loading finance applications…</div>';
    const {data,error}=await db.from('finance_applications').select('*').order('created_at',{ascending:false});
    if(error){$('list').innerHTML=`<div class="finance-admin-empty"><strong>Applications could not be loaded.</strong><br>${esc(error.message)}${error.code?` (${esc(error.code)})`:''}</div>`;return}
    render(data||[]);
  }
  async function showState(){const {data:{session}}=await db.auth.getSession();$('login').hidden=Boolean(session);$('app').hidden=!session;if(session){$('account').textContent=`Signed in as ${session.user.email}`;load()}}
  $('loginForm').addEventListener('submit',async event=>{event.preventDefault();$('loginMsg').textContent='Signing in…';const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});$('loginMsg').textContent=error?`Sign-in failed: ${error.message}`:'';if(!error)showState()});
  $('refresh').addEventListener('click',load);$('demo').addEventListener('click',()=>render([demo],true));$('signout').addEventListener('click',async()=>{await db.auth.signOut();showState()});
  showState();
})();
