(()=>{
  const db=supabase.createClient('https://dpsgtliddmdvfwjahkkq.supabase.co','sb_publishable_f-MRqpvq-FGsxQ7dBNIyKQ_r8MB1VM0'),$=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const datetime=value=>new Date(value).toLocaleString('en-CA',{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
  function application(row){const name=`${row.first_name||''} ${row.last_name||''}`.trim()||'Unnamed applicant';return `<article class="finance-application"><div class="finance-application-summary"><div class="finance-applicant-name"><span class="eyebrow red">FINANCE APPLICATION</span><h2>${esc(name)}</h2><p>Submitted ${esc(datetime(row.created_at))}</p></div><div class="finance-summary-item"><span>Status</span><strong class="finance-status">${esc(row.status||'New')}</strong></div><div class="finance-summary-item"><span>Vehicle</span><strong>${esc(row.vehicle_interest||'Not specified')}</strong></div><div class="finance-summary-item"><span>Phone</span><strong>${esc(row.phone||'—')}</strong></div><a class="btn finance-open-application" href="finance-application.html?id=${encodeURIComponent(row.id)}">Open Application</a></div></article>`}
  function render(rows){$('list').innerHTML=rows.length?rows.map(application).join(''):'<div class="finance-admin-empty">No finance applications have been submitted yet.</div>'}
  async function load(){$('list').innerHTML='<div class="finance-admin-empty">Loading finance applications…</div>';const{data,error}=await db.from('finance_applications').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML=`<div class="finance-admin-empty"><strong>Applications could not be loaded.</strong><br>${esc(error.message)}</div>`;return}render(data||[])}
  async function init(){const{data:{user}}=await db.auth.getUser();if(!user){location.replace('finance-admin-login.html');return}$('app').hidden=false;$('account').textContent=`Signed in as ${user.email}`;if(new URLSearchParams(location.search).get('deleted')==='1'){$('adminMessage').textContent='Application and all associated personal information were permanently deleted.';history.replaceState({},'',location.pathname)}load()}
  $('refresh').addEventListener('click',load);$('signout').addEventListener('click',async()=>{await db.auth.signOut();location.replace('finance-admin-login.html')});init();
})();
