const SUPABASE_URL="https://dpsgtliddmdvfwjahkkq.supabase.co",SUPABASE_KEY="sb_publishable_f-MRqpvq-FGsxQ7dBNIyKQ_r8MB1VM0";
const menuBtn=document.getElementById("menuBtn"),nav=document.getElementById("nav"),inventoryGrid=document.getElementById("inventoryGrid"),makeFilter=document.getElementById("makeFilter"),modelFilter=document.getElementById("modelFilter"),priceFilter=document.getElementById("priceFilter"),searchButton=document.getElementById("searchInventory");
document.getElementById("year")&&(document.getElementById("year").textContent=new Date().getFullYear());

const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const money=v=>Number.isFinite(Number(v))?new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(Number(v)):"$—";
const km=v=>Number.isFinite(Number(v))?`${new Intl.NumberFormat("en-CA").format(Number(v))} km`:"Mileage N/A";
let finance={apr:8.99,term_months:84,down_payment:0};
async function get(table,params={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${encodeURIComponent(table)}?${new URLSearchParams(params)}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`}});if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadFinance(){try{const x=await get("finance_settings",{select:"*",id:"eq.1"});if(x[0])finance=x[0]}catch(e){console.warn("Using default finance settings",e)}}
const TAX_RATE=.12,PAYMENT_BUFFER=1000,DISPLAY_TERM_MONTHS=72;function biweekly(price){const p=Math.max(0,Number(price||0)*(1+TAX_RATE)+PAYMENT_BUFFER),apr=Number(finance.apr||8.99)/100,n=DISPLAY_TERM_MONTHS/12*26;if(!p||!n)return 0;const annual=(1+apr/2)**2-1,r=(1+annual)**(1/26)-1;return r?p*r/(1-(1+r)**-n):p/n}
function paymentInline(price){return `<span class="featured-payment">or <b>${money(Math.round(biweekly(price)))}</b> bi-weekly</span>`}
function paymentNote(){return `<p class="featured-finance-note">Price incl. GST/PST. Financing based on 72 mo. with $0 down, no trade-in. OAC.</p>`}
function active(v){return["available","in stock","active"].includes(String(v.Status||v.status||"Available").toLowerCase())}
function featured(v){const x=v.Featured??v.featured??false;return x===true||String(x).toLowerCase()==="true"||Number(x)===1}
function featuredOrder(v){const n=Number(v.featured_order??v.FeaturedOrder);return Number.isFinite(n)&&n>0?n:Number.MAX_SAFE_INTEGER}
async function loadInventory(){try{await loadFinance();const all=(await get("Vehicles",{select:"*",order:"created_at.desc"})).filter(active);const photos=await get("vehicle_images",{select:"*",order:"is_primary.desc,sort_order.asc"});const imageMap=new Map();photos.forEach(p=>{const key=String(p.vehicle_id);if(!imageMap.has(key))imageMap.set(key,[]);imageMap.get(key).push(p.image_url)});
const makes=[...new Set(all.map(v=>v.Make||v.make).filter(Boolean))].sort(),models=[...new Set(all.map(v=>v.Model||v.model).filter(Boolean))].sort();
if(makeFilter)makeFilter.innerHTML='<option value="">Any Make</option>'+makes.map(x=>`<option>${esc(x)}</option>`).join("");
if(modelFilter)modelFilter.innerHTML='<option value="">Any Model</option>'+models.map(x=>`<option>${esc(x)}</option>`).join("");
if(priceFilter)priceFilter.innerHTML='<option value="">Any Price</option><option value="under-20000">Under $20,000</option><option value="20000-30000">$20,000–$29,999</option><option value="30000-50000">$30,000–$49,999</option><option value="50000-plus">$50,000+</option>';
const render=list=>{if(!list.length){inventoryGrid.innerHTML='<div class="inventory-empty">No featured vehicles yet. Check our full inventory for the latest arrivals.</div>';return}
inventoryGrid.innerHTML=list.slice(0,6).map(v=>{const title=`${v.Year||v.year||""} ${v.Make||v.make||""} ${v.Model||v.model||""}`.trim(),gallery=imageMap.get(String(v.id))||[],img=gallery[0],mileage=v.Mileage??v.mileage,price=v.Price??v.price,detail=`vehicle.html?id=${encodeURIComponent(v.id)}`;return `<article class="vehicle-card featured-card"><div class="vehicle-image ${img?"":"placeholder"}" data-gallery='${esc(JSON.stringify(gallery))}' data-index="0">${img?`<a class="vehicle-image-link" href="${detail}"><img src="${esc(img)}" alt="${esc(title)}" loading="lazy"></a>`:'<span>PHOTO COMING SOON</span>'}${gallery.length>1?`<button class="card-gallery-arrow prev" type="button" aria-label="Previous photo">‹</button><button class="card-gallery-arrow next" type="button" aria-label="Next photo">›</button><span class="photo-counter">1 / ${gallery.length}</span>`:""}</div><div class="vehicle-info"><p class="vehicle-year">FEATURED VEHICLE</p><h3><a class="vehicle-title-link" href="${detail}">${esc(title)}</a></h3><div class="vehicle-meta"><span>${esc(km(mileage))}</span><span>${esc(v.Transmission||v.transmission||"Automatic")}</span><span>Pre-Owned</span></div><div class="price-row featured-price-row"><div class="featured-price-group"><strong>${money(price)}</strong>${paymentInline(price)}</div><a href="${detail}">View Details →</a></div>${paymentNote()}</div></article>`}).join("");
document.querySelectorAll(".featured-card .vehicle-image[data-gallery]").forEach(box=>{const gallery=JSON.parse(box.dataset.gallery||"[]");let i=0;const img=box.querySelector("img"),counter=box.querySelector(".photo-counter");const change=dir=>{if(!gallery.length||!img)return;i=(i+dir+gallery.length)%gallery.length;img.src=gallery[i];box.dataset.index=i;if(counter)counter.textContent=`${i+1} / ${gallery.length}`};box.querySelector(".prev")?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();change(-1)});box.querySelector(".next")?.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();change(1)})})};
const apply=()=>{const make=makeFilter?.value||"",model=modelFilter?.value||"",range=priceFilter?.value||"";const matches=v=>{const p=Number(v.Price??v.price);const price=!range||(range==="under-20000"&&p<20000)||(range==="20000-30000"&&p>=20000&&p<30000)||(range==="30000-50000"&&p>=30000&&p<50000)||(range==="50000-plus"&&p>=50000);return(!make||(v.Make||v.make)===make)&&(!model||(v.Model||v.model)===model)&&price};const chosen=all.filter(featured).filter(matches).sort((a,b)=>featuredOrder(a)-featuredOrder(b));render(chosen)};
searchButton?.addEventListener("click",()=>{const q=new URLSearchParams();if(makeFilter?.value)q.set("make",makeFilter.value);if(modelFilter?.value)q.set("model",modelFilter.value);location.href=`inventory.html${q.toString()?`?${q}`:""}`});[makeFilter,modelFilter,priceFilter].forEach(el=>el?.addEventListener("change",apply));apply()
}catch(e){console.error(e);if(inventoryGrid)inventoryGrid.innerHTML='<div class="inventory-empty">We couldn\'t load inventory right now. Please try again shortly.</div>'}}
if(inventoryGrid)loadInventory();